### ISSUE TITLE
🧶 Custom class types

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/pandora#13]
By default, Pandora will initialise the following types:

- `PandoraCategory` - any category is of this type
- `PandoraEntity` - any entity object is of this type, also `PandoraCategory` is of this type
- `PandoraEntityInstance` - any instance is of this type. Instances are being created at runtime and only stored in the user data storage, not in the game storage

While this is useful, introducing something like an inventory system (https://github.com/bitbrain/pandora/issues/7) is difficult, as someone would need to 'guess' the attributes and properties of an item. It is also a problem when it comes to type-safety: ideally, implementing something like an inventory should only operate on items, but then it would be possible to assign other entities, e.g. NPCs to an inventory which does not really make sense logically. We also cannot guarantee that a `PandoraEntityInstance` has the required attributes.

## Solution

Introduce a new property on any `PandoraCategory` or `PandoraEntity` that is the path to the script/type defining that object. By default, it is set to the path of `PandoraEntityInstance` class but it can be overridden. The caveat is that any script mentioned here needs to be a child of `PandoraEntityInstance`.

- where would that config sit? Would it be rather part of the entity itself?
- how can I easily access the custom types? e.g. currently, we would need to do something like this:
```gdscript
var inventory_item = Pandora.get_entity_by_name("Iron Pickaxe") as InventoryItem
```
which is not very nice. Unless, we recommend doing something like this:
```gdscript
class_name ItemBackend

static func get_item(name:String) -> InventoryItem:
   return Pandora.get_entity_by_name(name) as InventoryItem
```
and then doing this instead:
```gdscript
var inventory_item = ItemBackend.get_item("Iron Pickaxe")
```

## Todo

- [x] resolve script type when loading an entity
- [x] fallback to PandoraEntity in case the script cannot be found/loaded
- [x] re-instantiate any PandoraEntity that was created in the editor
- [x] update inventory example to use ItemInstance rather than PandoraEntityInstance
